// Package attest provides attestation service client
package attest

import (
	"bytes"
	"crypto/ecdsa"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"math/big"
	"net/http"
	"strconv"
	"strings"
	"time"

	ethcrypto "github.com/ethereum/go-ethereum/crypto"
	ethecies "github.com/ethereum/go-ethereum/crypto/ecies"
)

// Client is the attestation service client
type Client struct {
	baseURL    string
	httpClient *http.Client
	teePrivKey *ecdsa.PrivateKey // TEE private key for signing
}

// Config holds client configuration
type Config struct {
	BaseURL string
	Timeout time.Duration
}

// NewClient creates a new attestation client
func NewClient(cfg *Config) *Client {
	timeout := cfg.Timeout
	if timeout == 0 {
		timeout = 30 * time.Second
	}

	return &Client{
		baseURL: cfg.BaseURL,
		httpClient: &http.Client{
			Timeout: timeout,
			Transport: &http.Transport{
				Proxy: nil,
			},
		},
	}
}

// SetTEEPrivateKey sets the TEE private key used for signing requests
// This is the key pair generated by the wrapper (secp256k1)
func (c *Client) SetTEEPrivateKey(privKey *ecdsa.PrivateKey) {
	c.teePrivKey = privKey
}

// SetTEEPrivateKeyFromHex sets the TEE private key from hex string
func (c *Client) SetTEEPrivateKeyFromHex(privKeyHex string) error {
	// Strip 0x prefix
	hexStr := privKeyHex
	if len(hexStr) >= 2 && hexStr[0:2] == "0x" {
		hexStr = hexStr[2:]
	}

	// Decode hex
	keyBytes, err := hex.DecodeString(hexStr)
	if err != nil {
		return fmt.Errorf("invalid hex key: %w", err)
	}

	// Use go-ethereum's ToECDSA to create secp256k1 private key
	privKey, err := ethcrypto.ToECDSA(keyBytes)
	if err != nil {
		return fmt.Errorf("failed to parse secp256k1 private key: %w", err)
	}

	c.teePrivKey = privKey
	return nil
}

// UnsealRequest is the request body for /v1/unseal (legacy)
type UnsealRequest struct {
	SealID     string `json:"seal_id"`
	PubKey     string `json:"pubkey"`
	ImageHash  string `json:"image_hash"`
	Signature  string `json:"signature"`
	Timestamp  int64  `json:"ts"`
}

// UnsealResponse is the response from /v1/unseal (legacy)
type UnsealResponse struct {
	Scheme      string `json:"scheme"`       // "ecies-secp256k1-aes256gcm"
	EncryptedKey string `json:"encrypted_key"` // Base64 or hex encoded encrypted agentSeal key
	ExpiresAt   int64  `json:"expires_at"`   // Unix timestamp
}

// ProvisionRequest is the request body for /provision (current API)
type ProvisionRequest struct {
	SealID           string `json:"seal_id"`
	ContainerPubkey  string `json:"container_pubkey"`
	ImageHash        string `json:"image_hash"`
	IssuedAt         int64  `json:"issued_at"`
	SandboxSignature string `json:"sandbox_signature"`
}

// ProvisionResponse is the response from /provision
type ProvisionResponse struct {
	EncryptedAgentSealPriv string `json:"encrypted_agent_seal_priv"` // Hex encoded ECIES encrypted key
}

// ErrorResponse represents an error response from the attestation service
type ErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Error codes
const (
	ErrCodeInvalidSignature = "INVALID_SIGNATURE"
	ErrCodeInvalidSealID    = "INVALID_SEAL_ID"
	ErrCodeInvalidImageHash = "INVALID_IMAGE_HASH"
	ErrCodeRateLimit        = "RATE_LIMIT"
	ErrCodeInternal         = "INTERNAL"
)

// Signature format constants
const (
	// SignatureHexLength is the expected length of a hex-encoded signature
	// Format: "0x" + 65 bytes * 2 hex chars = 132 chars
	SignatureHexLength = 132
	// SignatureBytesLength is the length of a raw signature in bytes
	SignatureBytesLength = 65
	// SignaturePrefix is the standard prefix for hex-encoded signatures
	SignaturePrefix = "0x"
)

// Unseal performs the unseal operation to get the agentSeal private key
func (c *Client) Unseal(sealID, pubKey, imageHash string) (*UnsealResponse, error) {
	// 1. Create timestamp
	ts := time.Now().Unix()

	// 2. Create signature: sign(keccak256("ImageAttestation:"+sealID+":"+pubKey+":"+imageHash+":"+ts))
	signature, err := c.createUnsealSignature(sealID, pubKey, imageHash, ts)
	if err != nil {
		return nil, fmt.Errorf("failed to create signature: %w", err)
	}

	// 3. Build request
	req := &UnsealRequest{
		SealID:    sealID,
		PubKey:    pubKey,
		ImageHash: imageHash,
		Signature: signature,
		Timestamp: ts,
	}

	// 4. Send to Attestor
	resp, err := c.sendUnsealRequest(req)
	if err != nil {
		return nil, fmt.Errorf("unseal request failed: %w", err)
	}

	return resp, nil
}

// createUnsealSignature creates signature for unseal request
// Format: keccak256("ImageAttestation:"+sealID+":"+pubkey+":"+imageHash+":"+ts)
// Then sign with TEE private key (secp256k1), V normalized to 27/28
func (c *Client) createUnsealSignature(sealID, pubKey, imageHash string, ts int64) (string, error) {
	if c.teePrivKey == nil {
		return "", fmt.Errorf("TEE private key not set")
	}

	// Create message: "ImageAttestation:"+sealID+":"+pubkey+":"+imageHash+":"+ts
	message := fmt.Sprintf("ImageAttestation:%s:%s:%s:%d", sealID, pubKey, imageHash, ts)

	// Keccak256 hash
	hash := ethcrypto.Keccak256([]byte(message))

	// Sign with TEE private key (secp256k1)
	// go-ethereum's Sign returns a 65-byte signature with V already normalized to 27/28
	signature, err := ethcrypto.Sign(hash, c.teePrivKey)
	if err != nil {
		return "", fmt.Errorf("signing failed: %w", err)
	}

	// Encode signature: 0x + 65 bytes
	return "0x" + hex.EncodeToString(signature), nil
}

// sendUnsealRequest sends HTTP POST to /v1/unseal
func (c *Client) sendUnsealRequest(req *UnsealRequest) (*UnsealResponse, error) {
	// Marshal body
	jsonData, err := json.Marshal(req)
	if err != nil {
		return nil, err
	}

	// Create request
	url := c.baseURL + "/v1/unseal"
	httpReq, err := http.NewRequest("POST", url, bytes.NewReader(jsonData))
	if err != nil {
		return nil, err
	}

	// Set headers
	httpReq.Header.Set("Content-Type", "application/json")

	// Send request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	// Read body
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}

	// Check status
	if resp.StatusCode != http.StatusOK {
		// Try to parse error response
		var errResp ErrorResponse
		if json.Unmarshal(body, &errResp) == nil && errResp.Code != "" {
			return nil, fmt.Errorf("attestor error: %s - %s", errResp.Code, errResp.Message)
		}
		return nil, fmt.Errorf("attestor returned status %d: %s", resp.StatusCode, string(body))
	}

	// Parse response
	var unsealResp UnsealResponse
	if err := json.Unmarshal(body, &unsealResp); err != nil {
		return nil, err
	}

	return &unsealResp, nil
}

// DecryptAgentSealKey decrypts the agentSeal key from the unseal response
// The scheme is "ecies-secp256k1-aes256gcm" - ECIES encryption with secp256k1 and AES-256-GCM
func (c *Client) DecryptAgentSealKey(encryptedKey string, TEEPrivateKey *ecdsa.PrivateKey) ([]byte, error) {
	// Strip 0x prefix if present
	hexStr := encryptedKey
	if len(hexStr) >= 2 && hexStr[0:2] == "0x" {
		hexStr = hexStr[2:]
	}

	// Parse encrypted key
	cipherText, err := hex.DecodeString(hexStr)
	if err != nil {
		return nil, fmt.Errorf("invalid hex: %w", err)
	}

	// Convert ECDSA private key to ECIES private key for secp256k1
	eciesPrivKey := ethecies.ImportECDSA(TEEPrivateKey)

	// Decrypt using ECIES with secp256k1
	// The encrypted data format: ephemeral public key + encrypted data + MAC
	plaintext, err := eciesPrivKey.Decrypt(cipherText, nil, nil)
	if err != nil {
		return nil, fmt.Errorf("ECIES decryption failed: %w", err)
	}

	return plaintext, nil
}

// DecryptSealedKey decrypts a sealed key using ECIES with secp256k1
// This is used to decrypt sealedKey → dataKey for intelligent data access
// The agentSealPriv must be a secp256k1 private key
func DecryptSealedKey(sealedKey []byte, agentSealPriv *ecdsa.PrivateKey) ([]byte, error) {
	if len(sealedKey) == 0 {
		return nil, errors.New("sealed key is empty")
	}
	if agentSealPriv == nil {
		return nil, errors.New("agent seal private key is nil")
	}

	// Convert ECDSA private key to ECIES private key for secp256k1
	eciesPrivKey := ethecies.ImportECDSA(agentSealPriv)

	// Decrypt using ECIES
	plaintext, err := eciesPrivKey.Decrypt(sealedKey, nil, nil)
	if err != nil {
		return nil, fmt.Errorf("ECIES decrypt sealed key failed: %w", err)
	}

	return plaintext, nil
}

// BytesToSecp256k1PrivateKey converts a 32-byte private key to secp256k1 ECDSA private key
// This is used to convert agentSealKey bytes to ECDSA for signing/decryption
func BytesToSecp256k1PrivateKey(keyBytes []byte) (*ecdsa.PrivateKey, error) {
	if len(keyBytes) != 32 {
		return nil, fmt.Errorf("invalid key length: expected 32 bytes, got %d", len(keyBytes))
	}

	// Use go-ethereum's ToECDSA which expects secp256k1
	privKey, err := ethcrypto.ToECDSA(keyBytes)
	if err != nil {
		return nil, fmt.Errorf("failed to parse secp256k1 private key: %w", err)
	}

	return privKey, nil
}

// Provision performs the provision operation to get the agentSeal private key
// Uses the /provision endpoint (current API)
func (c *Client) Provision(sealID, containerPubkey, imageHash string) (*ProvisionResponse, error) {
	// 1. Create timestamp
	ts := time.Now().Unix()

	// 2. Create signature: sign(keccak256("ImageAttestation:"+sealID+":"+pubkey+":"+imageHash+":"+ts))
	signature, err := c.createUnsealSignature(sealID, containerPubkey, imageHash, ts)
	if err != nil {
		return nil, fmt.Errorf("failed to create signature: %w", err)
	}

	// 3. Build request
	req := &ProvisionRequest{
		SealID:           "0x" + sealID,
		ContainerPubkey:  containerPubkey,
		ImageHash:        "0x" + strings.TrimPrefix(imageHash, "sha256:"),
		IssuedAt:         ts,
		SandboxSignature: signature,
	}

	// 4. Send to Attestor
	resp, err := c.sendProvisionRequest(req)
	if err != nil {
		return nil, fmt.Errorf("provision request failed: %w", err)
	}

	return resp, nil
}

// sendProvisionRequest sends HTTP POST to /provision
func (c *Client) sendProvisionRequest(req *ProvisionRequest) (*ProvisionResponse, error) {
	// Marshal body
	jsonData, err := json.Marshal(req)
	if err != nil {
		return nil, err
	}

	// Create request
	url := c.baseURL + "/provision"
	httpReq, err := http.NewRequest("POST", url, bytes.NewReader(jsonData))
	if err != nil {
		return nil, err
	}

	// Set headers
	httpReq.Header.Set("Content-Type", "application/json")

	// Send request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	// Read body
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}

	// Check status
	if resp.StatusCode != http.StatusOK {
		// Try to parse error response
		var errResp ErrorResponse
		if json.Unmarshal(body, &errResp) == nil && errResp.Code != "" {
			return nil, fmt.Errorf("attestor error: %s - %s", errResp.Code, errResp.Message)
		}
		return nil, fmt.Errorf("attestor returned status %d: %s", resp.StatusCode, string(body))
	}

	// Parse response
	var provisionResp ProvisionResponse
	if err := json.Unmarshal(body, &provisionResp); err != nil {
		return nil, err
	}

	return &provisionResp, nil
}

// GetAgentSealKey performs full provision flow and returns the decrypted key
// This is the main entry point for getting the agentSeal private key
func (c *Client) GetAgentSealKey(sealID, pubKey, imageHash string) ([]byte, error) {
	// 1. Perform provision (current API)
	resp, err := c.Provision(sealID, pubKey, imageHash)
	if err != nil {
		return nil, err
	}

	// 2. Decrypt agentSeal key using ECIES
	key, err := c.DecryptAgentSealKey(resp.EncryptedAgentSealPriv, c.teePrivKey)
	if err != nil {
		return nil, fmt.Errorf("failed to decrypt agentSeal key: %w", err)
	}

	return key, nil
}

// SetTEEKeyFromHex is a convenience method to set the TEE key from hex
// This should be called before Unseal()
func (c *Client) SetTEEKeyFromHex(privKeyHex string) error {
	return c.SetTEEPrivateKeyFromHex(privKeyHex)
}

// GetTEEAddress returns the Ethereum address derived from the TEE public key
func (c *Client) GetTEEAddress() (string, error) {
	if c.teePrivKey == nil {
		return "", fmt.Errorf("TEE private key not set")
	}

	// Use go-ethereum's PubkeyToAddress for proper Ethereum address derivation
	address := ethcrypto.PubkeyToAddress(c.teePrivKey.PublicKey)
	return address.Hex(), nil
}

// ValidateSignature validates a signature against the expected format
func ValidateSignature(signature string) error {
	if len(signature) != SignatureHexLength {
		return fmt.Errorf("invalid signature length: expected %d chars (%s + %d hex), got %d",
			SignatureHexLength, SignaturePrefix, SignatureBytesLength*2, len(signature))
	}

	if signature[0:2] != SignaturePrefix {
		return fmt.Errorf("signature must start with %s", SignaturePrefix)
	}

	hexStr := signature[2:]
	_, err := hex.DecodeString(hexStr)
	if err != nil {
		return fmt.Errorf("invalid hex signature: %w", err)
	}

	return nil
}

// ParseSignature parses a signature into r, s, v components
func ParseSignature(signature string) (r, s *big.Int, v byte, err error) {
	if err := ValidateSignature(signature); err != nil {
		return nil, nil, 0, err
	}

	hexStr := signature[len(SignaturePrefix):]
	sigBytes, _ := hex.DecodeString(hexStr)

	r = new(big.Int).SetBytes(sigBytes[0:32])
	s = new(big.Int).SetBytes(sigBytes[32:64])
	v = sigBytes[64]

	return r, s, v, nil
}

// FormatSignature formats r, s, v into a signature string
func FormatSignature(r, s *big.Int, v byte) string {
	sigBytes := make([]byte, SignatureBytesLength)
	copy(sigBytes[0:32], r.Bytes())
	copy(sigBytes[32:64], s.Bytes())
	sigBytes[64] = v

	return SignaturePrefix + hex.EncodeToString(sigBytes)
}

// Timestamp is a helper for getting current timestamp
func Timestamp() int64 {
	return time.Now().Unix()
}

// FormatTimestamp formats a timestamp to string
func FormatTimestamp(ts int64) string {
	return strconv.FormatInt(ts, 10)
}

// ── Status Report ─────────────────────────────────────────────────────────────

// StatusReportRequest is the request body for /status
type StatusReportRequest struct {
	SealID            string `json:"seal_id"`
	Status            string `json:"status"`
	ErrorDetail       string `json:"error_detail,omitempty"`
	AgentSealSignature string `json:"agent_seal_signature"`
}

// StatusReportResponse is the response from /status
type StatusReportResponse struct {
	Accepted bool   `json:"accepted"`
	Message  string `json:"message,omitempty"`
}

// ReportStatus sends a status report to the Attestor
// The message format is: "StatusReport:<seal_id_0x>:<status>:<error_detail>"
// Signed with agent_seal_priv using Keccak256 + secp256k1, V normalized to 27/28
func (c *Client) ReportStatus(agentSealPriv *ecdsa.PrivateKey, sealID, status, errorDetail string) (*StatusReportResponse, error) {
	// 1. Create canonical message
	msg := fmt.Sprintf("StatusReport:0x%s:%s:%s", sealID, status, errorDetail)

	// 2. Keccak256 hash
	hash := ethcrypto.Keccak256([]byte(msg))

	// 3. Sign with agent_seal_priv (secp256k1)
	signature, err := ethcrypto.Sign(hash, agentSealPriv)
	if err != nil {
		return nil, fmt.Errorf("signing failed: %w", err)
	}

	// 4. Normalize V to 27/28 (crypto.Sign returns 0/1)
	signature[64] += 27

	// 5. Build request
	req := &StatusReportRequest{
		SealID:            "0x" + sealID,
		Status:            status,
		ErrorDetail:       errorDetail,
		AgentSealSignature: "0x" + hex.EncodeToString(signature),
	}

	// 6. Send to Attestor
	return c.sendStatusReportRequest(req)
}

// sendStatusReportRequest sends HTTP POST to /status
func (c *Client) sendStatusReportRequest(req *StatusReportRequest) (*StatusReportResponse, error) {
	// Marshal body
	jsonData, err := json.Marshal(req)
	if err != nil {
		return nil, err
	}

	// Create request
	url := c.baseURL + "/status"
	httpReq, err := http.NewRequest("POST", url, bytes.NewReader(jsonData))
	if err != nil {
		return nil, err
	}

	// Set headers
	httpReq.Header.Set("Content-Type", "application/json")

	// Send request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	// Read body
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}

	// Check status
	if resp.StatusCode != http.StatusOK {
		// Try to parse error response
		var errResp ErrorResponse
		if json.Unmarshal(body, &errResp) == nil && errResp.Code != "" {
			return nil, fmt.Errorf("attestor error: %s - %s", errResp.Code, errResp.Message)
		}
		return nil, fmt.Errorf("attestor returned status %d: %s", resp.StatusCode, string(body))
	}

	// Parse response
	var statusResp StatusReportResponse
	if err := json.Unmarshal(body, &statusResp); err != nil {
		return nil, err
	}

	return &statusResp, nil
}
